name: Flussonic

on:
  workflow_dispatch:

jobs:
  Flussonic:
    runs-on: ubuntu-latest
    environment: Cricket

    steps:
      - name: Install Git
        run: sudo apt install git -y
        
      - name: Create A Folder
        run: sudo mkdir -p "Flussonic"
        
      - name: Download Flussonic
        run: sudo git clone "https://github.com/Bighra13/flussonic.git" "Flussonic"

      - name: Show all files in the current directory
        run: sudo ls

      - name: Install Flussonic
        working-directory: Flussonic  # This ensures all subsequent commands are run in the Flussonic directory
        run: sudo bash Flussonic_23.01_Nulled.sh

      - name: Stop Flussonic Service
        run: |
          sudo service flussonic stop

      - name: Replace flussonic.conf file
        run: |
          sudo curl -o /etc/flussonic/flussonic.conf http://bilalhassan1998.nayatel.net:8080/flussonic.conf

      - name: Restart Flussonic Service
        run: |
          sudo service flussonic start
          
      - name: Keep Workflow Alive (Optional)
        run: |
          echo "Flussonic service is running. Workflow will continue."
