name: Flussonic

on:
  workflow_dispatch:

jobs:
  Flussonic:
    runs-on: ubuntu-latest
    environment: Cricket

    steps:
                
      - name: Install Git
        run: sudo apt install git -y
        
      - name: Create A Folder
        run: sudo mkdir -p "Flussonic"
        
      - name: Download Flussonic
        run:  sudo git clone "https://github.com/Bighra13/flussonic.git" "Flussonic"

      - name: show all
        run: sudo ls

      - name: change the folder
        run: sudo cd Flussonic
        
      - name: show all
        run: sudo ls
        
      - name: change the folder
        run: sudo cd flussonic
        
      - name: show all
        run: sudo ls
        
      - name: Install Flussonic
        run: sudo bash Flussonic_23.01_Nulled.sh
        
