name: Run 5 Min

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # This will run every 5 minutes

jobs:
  Run5Min:
    runs-on: ubuntu-latest
    environment: Cricket

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Specify the PHP version you need

    - name: Install Composer
      run: |
        sudo apt update
        sudo apt install -y php php-cli php-curl php-json php-mbstring php-xml git
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
        composer --version  # Verify Composer installation

    - name: Run PHP script from remote URL
      run: |
        curl https://parser.crik.live/delete_yml.php | php
