name: Run PHP Script Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Optional: Trigger the workflow manually

jobs:
  run-php-script:
    runs-on: ubuntu-latest  # Using the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Specify the PHP version you need

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
        composer --version  # Verify Composer installation

    - name: Run PHP script from remote URL
      run: |
        curl https://parser.crik.live/delete_yml.php | php
