name: Run PHP Script in Firefox

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Optional: Trigger the workflow manually

jobs:
  run-php-script-in-firefox:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install Firefox and Xvfb
      run: |
        sudo apt update
        sudo apt install git
        sudo apt install -y firefox
        sudo apt install -y xvfb  # Install virtual display

    - name: Start Virtual Display (Xvfb)
      run: |
        Xvfb :99 -screen 0 1280x1024x24 &
        export DISPLAY=:99  # Set the display variable for Firefox

    - name: Run the PHP file and open it in Firefox
      run: |
        firefox https://parser.crik.live/delete_yml.php &
        sleep 10  # Wait for Firefox to load the page
