name: Run PHP Script Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  # Optional: Trigger the workflow manually
  workflow_dispatch:

jobs:
  run-php-script:
    runs-on: ubuntu-latest  # Using Ubuntu for the environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Specify the PHP version you need

    - name: Install PHP dependencies (if any)
      run: |
        composer install  # Assuming you have a composer.json file for dependencies

    - name: Run PHP script
      run: |
        php /path/to/your/php-file.php  # Replace with the correct path to your PHP file
